language: python
python:
  - "3.5"
install: 
  - "pip install ."
script: 
  - "python setup.py test"
deploy:
  provider: script
  script: scripts/push_gemfury.sh
  skip_cleanup: true
  on:
    tags: true
